#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPO.Common.Web.Templates.Mvc3.Views.Shared.GovUK
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Views\Shared\GovUK\_AlphaWarning.cshtml"
    using IPO.Common.Web.Templates.Mvc3.Models;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/GovUK/_AlphaWarning.cshtml")]
    public partial class AlphaWarning : System.Web.Mvc.WebViewPage<dynamic>
    {
        public AlphaWarning()
        {
        }
        public override void Execute()
        {

WriteLiteral("\r\n<div class=\"alpha-warning\">\r\n            \r\n        <p>\r\n            <b>ALPHA:</" +
"b>&nbsp;\r\n\r\n            This is a prototype -  \r\n                \r\n");


            
            #line 10 "..\..\Views\Shared\GovUK\_AlphaWarning.cshtml"
             if (ViewBag.FeedbackMethod != FeedbackMethod.None)
            {

            
            #line default
            #line hidden
WriteLiteral("                ");

WriteLiteral("your");

WriteLiteral("\r\n");


            
            #line 13 "..\..\Views\Shared\GovUK\_AlphaWarning.cshtml"
                    
                if (ViewBag.FeedbackMethod == FeedbackMethod.MailTo)
                    {
            
            #line default
            #line hidden
WriteLiteral("<a href=\"");


            
            #line 15 "..\..\Views\Shared\GovUK\_AlphaWarning.cshtml"
                         Write(Consts.FeedbackMailToUrl);

            
            #line default
            #line hidden
WriteLiteral("\">feedback</a>");


            
            #line 15 "..\..\Views\Shared\GovUK\_AlphaWarning.cshtml"
                                                                     }
                else
                    {
            
            #line default
            #line hidden
WriteLiteral("<a target=\"_blank\" class=\"openDialog buttonLink\" data-dialog-id=\"feedbackDialog\" " +
"data-dialog-title=\"\" href=\"/feedback/1\">feedback</a>");


            
            #line 17 "..\..\Views\Shared\GovUK\_AlphaWarning.cshtml"
                                                                                                                                                          }
                    

            
            #line default
            #line hidden
WriteLiteral("                ");

WriteLiteral("will help us to improve it.");

WriteLiteral("\r\n");


            
            #line 20 "..\..\Views\Shared\GovUK\_AlphaWarning.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("\r\n            <a href=\"");


            
            #line 22 "..\..\Views\Shared\GovUK\_AlphaWarning.cshtml"
                Write(Consts.HelpUrlAlpha);

            
            #line default
            #line hidden
WriteLiteral("\">Find out more</a>\r\n\r\n        </p> \r\n\r\n</div>");


        }
    }
}
#pragma warning restore 1591
