#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPO.Common.Web.Templates.Mvc3.Views.Shared.GovUK
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    
    #line 1 "..\..\Views\Shared\GovUK\_BetaWarning.cshtml"
    using System.Web.Mvc.Html;
    
    #line default
    #line hidden
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 2 "..\..\Views\Shared\GovUK\_BetaWarning.cshtml"
    using IPO.Common.Web.Templates.Mvc3.Models;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/GovUK/_BetaWarning.cshtml")]
    public partial class BetaWarning : System.Web.Mvc.WebViewPage<dynamic>
    {
        public BetaWarning()
        {
        }
        public override void Execute()
        {


WriteLiteral("\r\n<div class=\"beta-warning\">\r\n            \r\n        <p>\r\n            <b>BETA:</b>" +
"&nbsp;\r\n\r\n            This is a new service -  \r\n                \r\n");


            
            #line 11 "..\..\Views\Shared\GovUK\_BetaWarning.cshtml"
             if (ViewBag.FeedbackMethod != FeedbackMethod.None)
            {

            
            #line default
            #line hidden
WriteLiteral("                ");

WriteLiteral("your");

WriteLiteral("\r\n");


            
            #line 14 "..\..\Views\Shared\GovUK\_BetaWarning.cshtml"
                    
                
            
            #line default
            #line hidden
            
            #line 15 "..\..\Views\Shared\GovUK\_BetaWarning.cshtml"
           Write(Html.Partial("~/Views/Shared/GovUK/_FeedbackLink.cshtml"));

            
            #line default
            #line hidden
            
            #line 15 "..\..\Views\Shared\GovUK\_BetaWarning.cshtml"
                                                                          
                    

            
            #line default
            #line hidden
WriteLiteral("                ");

WriteLiteral("will help us to improve it.");

WriteLiteral("\r\n");


            
            #line 18 "..\..\Views\Shared\GovUK\_BetaWarning.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("            \r\n            <a target=\"_blank\" href=\"");


            
            #line 20 "..\..\Views\Shared\GovUK\_BetaWarning.cshtml"
                                Write(Consts.HelpUrlBeta);

            
            #line default
            #line hidden
WriteLiteral("\">Find out more about the beta phase.</a>\r\n\r\n        </p>\r\n\r\n</div>");


        }
    }
}
#pragma warning restore 1591
