#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPO.Common.Web.Templates.Mvc3.Views.Shared.GovUK
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Views\Shared\GovUK\_FeedbackLink.cshtml"
    using IPO.Common.Web.Templates.Mvc3.Models;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/GovUK/_FeedbackLink.cshtml")]
    public partial class FeedbackLink : System.Web.Mvc.WebViewPage<dynamic>
    {
        public FeedbackLink()
        {
        }
        public override void Execute()
        {

WriteLiteral("\r\n");


            
            #line 3 "..\..\Views\Shared\GovUK\_FeedbackLink.cshtml"
 if (ViewBag.FeedbackMethod == FeedbackMethod.MailTo)
    {
            
            #line default
            #line hidden
WriteLiteral("<a href=\"");


            
            #line 4 "..\..\Views\Shared\GovUK\_FeedbackLink.cshtml"
         Write(Consts.FeedbackMailToUrl);

            
            #line default
            #line hidden
WriteLiteral("\">feedback</a>");


            
            #line 4 "..\..\Views\Shared\GovUK\_FeedbackLink.cshtml"
                                                     }
else
    {
            
            #line default
            #line hidden
WriteLiteral("<a target=\"_blank\" class=\"openDialog buttonLink\" data-dialog-id=\"feedbackDialog\" " +
"data-dialog-title=\"\" href=\"/feedback/1\">feedback</a>");


            
            #line 6 "..\..\Views\Shared\GovUK\_FeedbackLink.cshtml"
                                                                                                                                          }
            
            #line default
            #line hidden

        }
    }
}
#pragma warning restore 1591
