#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPO.Common.Web.Templates.Mvc3.Views.Shared.GovUK
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/GovUK/_LayoutBasic.cshtml")]
    public partial class LayoutBasic : System.Web.Mvc.WebViewPage<dynamic>
    {
        public LayoutBasic()
        {
        }
        public override void Execute()
        {

            
            #line 1 "..\..\Views\Shared\GovUK\_LayoutBasic.cshtml"
  
    Layout = null;


            
            #line default
            #line hidden
WriteLiteral("\r\n<!DOCTYPE html>\r\n\r\n<html>\r\n<head>\r\n    <title>");


            
            #line 9 "..\..\Views\Shared\GovUK\_LayoutBasic.cshtml"
      Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral(@"</title>
    <script src=""/assets/scripts/jquery/jquery-1.7.1.min.js"" type=""text/javascript""></script>

    <link href=""/assets/template/stylesheets/govuk-template.css"" media=""screen"" rel=""stylesheet"" type=""text/css"" />
    
</head>
<body>
    <div>
        ");


            
            #line 17 "..\..\Views\Shared\GovUK\_LayoutBasic.cshtml"
   Write(RenderBody());

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n</body>\r\n</html>\r\n");


        }
    }
}
#pragma warning restore 1591
