#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPO.Common.Web.Templates.Mvc3.Views.Shared.GovUK
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/GovUK/Error.cshtml")]
    public partial class Error : System.Web.Mvc.WebViewPage<dynamic>
    {
        public Error()
        {
        }
        public override void Execute()
        {

            
            #line 1 "..\..\Views\Shared\GovUK\Error.cshtml"
  
    Layout = "~/Views/Shared/GovUK/_Layout.cshtml";


            
            #line default
            #line hidden
WriteLiteral("<h2>Sorry, an error occurred while processing your request.\r\n</h2>\r\n");


        }
    }
}
#pragma warning restore 1591
